services:
  # Aplicación principal Django + React
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
    depends_on:
      - redis
    networks:
      - agencia_network

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agencia_network

  # Nginx proxy (opcional - descomentamos si es necesario)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - static_volume:/var/www/static:ro
  #     - media_volume:/var/www/media:ro
  #   depends_on:
  #     - web
  #   networks:
  #     - agencia_network

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  agencia_network:
    driver: bridge
