export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// Categories
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS';
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS';
export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

// Blog
export const BLOG_LOADING = 'BLOG_LOADING';
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS';
export const BLOG_DETAIL_SUCCESS = 'BLOG_DETAIL_SUCCESS';
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS';
export const BLOG_UPDATE_SUCCESS = 'BLOG_UPDATE_SUCCESS';
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS';
export const BLOG_ERROR = 'BLOG_ERROR';

// Services
export const SERVICES_LOADING = 'SERVICES_LOADING';
export const SERVICES_LIST_SUCCESS = 'SERVICES_LIST_SUCCESS';
export const SERVICES_DETAIL_SUCCESS = 'SERVICES_DETAIL_SUCCESS';
export const SERVICES_CREATE_SUCCESS = 'SERVICES_CREATE_SUCCESS';
export const SERVICES_UPDATE_SUCCESS = 'SERVICES_UPDATE_SUCCESS';
export const SERVICES_DELETE_SUCCESS = 'SERVICES_DELETE_SUCCESS';
export const SERVICES_ERROR = 'SERVICES_ERROR';

// Service Categories
export const SERVICE_CATEGORIES_LOADING = 'SERVICE_CATEGORIES_LOADING';
export const SERVICE_CATEGORIES_LIST_SUCCESS = 'SERVICE_CATEGORIES_LIST_SUCCESS';
export const SERVICE_CATEGORIES_CREATE_SUCCESS = 'SERVICE_CATEGORIES_CREATE_SUCCESS';
export const SERVICE_CATEGORIES_UPDATE_SUCCESS = 'SERVICE_CATEGORIES_UPDATE_SUCCESS';
export const SERVICE_CATEGORIES_DELETE_SUCCESS = 'SERVICE_CATEGORIES_DELETE_SUCCESS';
export const SERVICE_CATEGORIES_ERROR = 'SERVICE_CATEGORIES_ERROR';

// Cases
export const CASES_LOADING = 'CASES_LOADING';
export const CASES_LIST_SUCCESS = 'CASES_LIST_SUCCESS';
export const CASES_DETAIL_SUCCESS = 'CASES_DETAIL_SUCCESS';
export const CASES_CREATE_SUCCESS = 'CASES_CREATE_SUCCESS';
export const CASES_UPDATE_SUCCESS = 'CASES_UPDATE_SUCCESS';
export const CASES_DELETE_SUCCESS = 'CASES_DELETE_SUCCESS';
export const CASES_ERROR = 'CASES_ERROR';

// Contacts
export const CONTACTS_LOADING = 'CONTACTS_LOADING';
export const CONTACTS_LIST_SUCCESS = 'CONTACTS_LIST_SUCCESS';
export const CONTACTS_UPDATE_SUCCESS = 'CONTACTS_UPDATE_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';

// Admin Users
export const ADMIN_USERS_LOADING = 'ADMIN_USERS_LOADING';
export const ADMIN_USERS_LIST_SUCCESS = 'ADMIN_USERS_LIST_SUCCESS';
export const ADMIN_USERS_UPDATE_SUCCESS = 'ADMIN_USERS_UPDATE_SUCCESS';
export const ADMIN_USERS_ERROR = 'ADMIN_USERS_ERROR';

