# Generated by Django 6.0.4 on 2026-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de lectura en minutos', null=True),
        ),
    ]
